parameters:

    spotify.api.baseurl: "https://api.spotify.com/"
    spotify.api.mapper.class: "Mmoreram\\SpotifyApiBundle\\Mapper\\SpotifyMapper"
    spotify.api.search.class: "Mmoreram\\SpotifyApiBundle\\Services\\SpotifyApiSearch"
    spotify.api.lookup.class: "Mmoreram\\SpotifyApiBundle\\Services\\SpotifyApiLookup"
